### PR TITLE
Update cs_CZ.lang

### PR DESCRIPTION
**Pull request by DeRigeurEx**
add missing command. ROWS :20-26
add ROW:1083 as FIX for ROW:811 (tested on MC1710-v9610)
deleted lot  # corrected a few errors in translation ;)

### CODE REVIEW

**Comment by CovertJaguar** [comment]
Did I manually merge this? I think I did...

**Comment by CovertJaguar** [comment]
Wait no, I don't think I did....why can't it be merged automatically I wonder...

**Comment by DeRigeurEx** [comment]
yes, I wonder too ;)

**Comment by CovertJaguar** [comment]
See #293

**Pull request closed without merging**
